local Notification = require(game:GetService("ReplicatedStorage").Notification)
Notification.new("<Color=Yellow> Khánh Băng là số 1 <Color=/>"):Display()
Notification.new("<Color=Red> Khánh Băng dễ thương <Color=/>"):Display()
Notification.new("<Color=Blue> Khánh Băng cute  <Color=/>"):Display()
print("yêu khánh băng lắm")
print("khánh băng là số 1")
